### ISSUE TITLE
Index ANO faltando no array

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/dados#107]
`production.ERROR: Undefined index: ANO (View: /var/www/dados.fflch.usp.br/resources/views/programas/pessoa.blade.php) {"view":{"view":"/var/www/dados.fflch.usp.br/resources/views/programas/pessoa.blade.php`

@st-ricardof @gabrielareisg

**Comment by gabrielareisg** [comment]
pode fechar
