### ISSUE TITLE
production.ERROR: Undefined index: INTEGRANTES-DO-PROJETO

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/dados#108]
/var/www/trabalhoacademico.fflch.usp.br/app/Models/Agendamento.php:116)
   Mar 26 13:24:43 php7 portal-de-dados[18414]: [2021-03-26 13:24:43]
   production.ERROR: Undefined index: INTEGRANTES-DO-PROJETO
   {"exception":"[object] (ErrorException(code: 0): Undefined index:
   INTEGRANTES-DO-PROJETO at
   /var/www/dados.fflch.usp.br/vendor/uspdev/replicado/src/Lattes.php:2189
   )
@st-ricardof  @ricardfo

**Comment by gabrielareisg** [comment]
pode fechar
